In [ ]:
# Cell 1 — Imports
import pandas as pd
import ast

### Loading data to dataframe

In [135]:
df = pd.read_csv("data/scraped_jobs_raw.csv")
df.head(20)

,title,company,location,work_mode,job_type,skills,salary,date_posted,experience_level,education,source,job_url
0,Data Scientist,"Comscore, Inc.","Pune, Maharashtra, India",NaN,fulltime,"['Linux', 'Python', 'R', 'SQL', 'Spark']",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/data-scientis...
1,"Senior Data Scientist, Agentic AI (Insurance U...",Guardian Life,"New York, New York, United States",NaN,fulltime,"['Git', 'PyTorch', 'Python', 'TensorFlow']",$118980 - $195465,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-data-s...
2,Financial Crimes - Senior Data Scientist,KeyBank,"Cleveland, Ohio, United States",NaN,fulltime,"['Python', 'SAS']",$94000 - $175000,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/financial-cri...
3,"Research Scientist – Computer Graphics, Vision...",Eyeline,"Los Angeles, California, United States",NaN,fulltime,['Python'],$100000 - $320000,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/research-scie...
4,Emerging Talent – Computer Vision Engineering ...,Baker Hughes,"Florence, Tuscany, Italy",NaN,fulltime,['Python'],NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/emerging-tale...
5,Senior / Staff Machine Learning Engineer,Shiftsmart,"New York, New York, United States",NaN,fulltime,"['GCP', 'MongoDB', 'Python', 'SQL', 'Scikit-Le...",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-machin...
6,Principal Machine Learning Scientist (US Remote),Turnitin,"Remote, , United States",NaN,fulltime,"['AWS Batch', 'AWS EC2', 'AWS Lambda', 'AWS Sa...",$147300 - $245000,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/principal-mac...
7,Data Scientist (H/F) - CDI,Unibail-Rodamco-Westfield,"Paris, Île-de-France, France",NaN,fulltime,"['BigQuery', 'GCP', 'Power BI', 'Python', 'SQL']",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/data-scientis...
8,Senior Data Scientist,GE HealthCare,"Bengaluru, Karnataka, India",NaN,fulltime,"['AWS', 'Azure', 'Keras', 'PyTorch', 'Python']",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-data-s...
9,Data Scientist,Kyndryl,"Gurgaon, Haryana, India",NaN,fulltime,"['AWS', 'Azure', 'C/C++', 'GCP', 'MLOps']",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/data-scientis...
10,Senior Machine Learning Engineer,Razer Inc.,"Chengdu, , China",NaN,fulltime,"['PyTorch', 'Python', 'R', 'TensorFlow']",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-machin...
11,"Senior Machine Learning Engineer, Ads Research",The Walt Disney Company,"Seattle, Washington, United States",NaN,fulltime,"['Java', 'PyTorch', 'Python', 'SQL', 'TensorFl...",$141900 - $199400,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-machin...
12,Machine Learning Signal Processing Engineer,Leidos,"Ann Arbor, Michigan, United States",NaN,fulltime,"['C++', 'MATLAB', 'PyTorch', 'Python', 'Scikit...",$69550 - $125725,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/machine-learn...
13,Senior Data Scientist,Accelleron,"Mohali, Punjab, India",NaN,fulltime,['Python'],NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-data-s...
14,Senior Data Scientist,Moneris,"Toronto, Ontario, Canada",NaN,fulltime,"['Databricks', 'Git', 'Power BI', 'Prophet', '...",CAD $116595 - CAD $166095,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-data-s...
15,Sr. Data Scientist (Content Security),Trend Micro,"Taipei, , Taiwan",NaN,fulltime,"['AWS EMR', 'Airflow', 'Azure Databricks', 'Ku...",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/sr-data-scien...
16,Senior AI / Computer Vision Engineer (Robotics...,Jabil,"Remote, , , Poland",NaN,fulltime,"['C++', 'Linux', 'Python', 'ROS']",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-ai--co...
17,Computer Vision Engineer,Prozis,"Maia, , Portugal",NaN,fulltime,"['C++', 'NumPy', 'OpenCV', 'PyTorch', 'Python']",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/computer-visi...
18,Applied AI Engineer (Startups),Anthropic,"London, England, United Kingdom",NaN,fulltime,['Python'],£225000 - £240000,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/applied-ai-en...
19,Sr. Data Engineer - AI ML,Assent,"Pune, Maharashtra, India",NaN,fulltime,"['AWS', 'Airflow', 'FAISS', 'Milvus', 'Neo4J']",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/sr-data-engin...

In [136]:
# 4290 rows and 12 Columns
# Skills shown as str even thoough it has to be list
# Salary is a number

print(df.shape)
print(df.dtypes)

(4290, 12)
title                   str
company                 str
location                str
work_mode               str
job_type                str
skills                  str
salary                  str
date_posted             str
experience_level    float64
education           float64
source                  str
job_url                 str
dtype: object

### Checking How many null values and where


To-Do:
- For 'date_posted' we will assume it was 2026-03-09 for the null values
- Experience Level and Education will be decided through LLM via skills and role
- some 'work_mode' values will be taken from location

In [137]:
df.isnull().sum()

title                  0
company                0
location               0
work_mode           3246
job_type            1044
skills                 0
salary              2896
date_posted         3246
experience_level    4290
education           4290
source                 0
job_url                0
dtype: int64

### Convert 'Skills' to List

In [138]:
df["skills"] = df["skills"].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else [])

In [139]:
df.head()

,title,company,location,work_mode,job_type,skills,salary,date_posted,experience_level,education,source,job_url
0,Data Scientist,"Comscore, Inc.","Pune, Maharashtra, India",NaN,fulltime,"[Linux, Python, R, SQL, Spark]",NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/data-scientis...
1,"Senior Data Scientist, Agentic AI (Insurance U...",Guardian Life,"New York, New York, United States",NaN,fulltime,"[Git, PyTorch, Python, TensorFlow]",$118980 - $195465,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-data-s...
2,Financial Crimes - Senior Data Scientist,KeyBank,"Cleveland, Ohio, United States",NaN,fulltime,"[Python, SAS]",$94000 - $175000,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/financial-cri...
3,"Research Scientist – Computer Graphics, Vision...",Eyeline,"Los Angeles, California, United States",NaN,fulltime,[Python],$100000 - $320000,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/research-scie...
4,Emerging Talent – Computer Vision Engineering ...,Baker Hughes,"Florence, Tuscany, Italy",NaN,fulltime,[Python],NaN,NaN,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/emerging-tale...

In [140]:
df.tail()

,title,company,location,work_mode,job_type,skills,salary,date_posted,experience_level,education,source,job_url
4285,Salesforce Experience Architect AI and Agentforce,"NeuraFlash, Part of Accenture",Remote - United States,remote,NaN,"[Salesforce, Architect, Amazon]",NaN,2026-01-10T14:00:33+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-salesf...
4286,Current openings,Remote - Referral Board,💰 Upgrade to Premium to see salary,remote,NaN,[],NaN,2026-01-10T14:00:11+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-curren...
4287,Principal DevSecOps Engineer,GHX,USA,remote,NaN,"[Technical, Software, Cloud]",NaN,2026-01-10T13:00:40+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-princi...
4288,Lead .NET Engineer,Excella,Arlington,remote,NaN,"[Support, Growth, Lead]",NaN,2026-01-10T13:00:24+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-lead-n...
4289,2D Game Artist Co op Intern,A Thinking Ape,💰 Upgrade to Premium to see salary,remote,NaN,"[Game, Mobile, Management]",NaN,2026-01-09T23:00:41+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-2d-gam...

### Filling up NaN with a default date

In [141]:
df["date_posted"] = df["date_posted"].fillna("2026-03-09")
df["date_posted"] = pd.to_datetime(df["date_posted"], format="mixed", utc=True)

In [142]:
df.head()

,title,company,location,work_mode,job_type,skills,salary,date_posted,experience_level,education,source,job_url
0,Data Scientist,"Comscore, Inc.","Pune, Maharashtra, India",NaN,fulltime,"[Linux, Python, R, SQL, Spark]",NaN,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/data-scientis...
1,"Senior Data Scientist, Agentic AI (Insurance U...",Guardian Life,"New York, New York, United States",NaN,fulltime,"[Git, PyTorch, Python, TensorFlow]",$118980 - $195465,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-data-s...
2,Financial Crimes - Senior Data Scientist,KeyBank,"Cleveland, Ohio, United States",NaN,fulltime,"[Python, SAS]",$94000 - $175000,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/financial-cri...
3,"Research Scientist – Computer Graphics, Vision...",Eyeline,"Los Angeles, California, United States",NaN,fulltime,[Python],$100000 - $320000,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/research-scie...
4,Emerging Talent – Computer Vision Engineering ...,Baker Hughes,"Florence, Tuscany, Italy",NaN,fulltime,[Python],NaN,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/emerging-tale...

### Replacing "location — some remoteok rows show "🔥 Upgrade to Premium to see salary" in the location field. That's a scraper issue — remoteok was putting paywalled content into the location. Not worth re-scraping, just clean those out." with np.nan

In [143]:
df.loc[df["location"].str.contains("Upgrade to Premium", na=False), "location"] = None

In [144]:
df.tail()

,title,company,location,work_mode,job_type,skills,salary,date_posted,experience_level,education,source,job_url
4285,Salesforce Experience Architect AI and Agentforce,"NeuraFlash, Part of Accenture",Remote - United States,remote,NaN,"[Salesforce, Architect, Amazon]",NaN,2026-01-10 14:00:33+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-salesf...
4286,Current openings,Remote - Referral Board,NaN,remote,NaN,[],NaN,2026-01-10 14:00:11+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-curren...
4287,Principal DevSecOps Engineer,GHX,USA,remote,NaN,"[Technical, Software, Cloud]",NaN,2026-01-10 13:00:40+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-princi...
4288,Lead .NET Engineer,Excella,Arlington,remote,NaN,"[Support, Growth, Lead]",NaN,2026-01-10 13:00:24+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-lead-n...
4289,2D Game Artist Co op Intern,A Thinking Ape,NaN,remote,NaN,"[Game, Mobile, Management]",NaN,2026-01-09 23:00:41+00:00,NaN,NaN,remoteok,https://remoteok.com/remote-jobs/remote-2d-gam...

### filling 'work_mode'

In [145]:
df.loc[df["location"].str.contains("worldwide|anywhere|remote", case=False, na=False), "work_mode"] = "remote"

In [146]:
df.loc[~df["location"].str.contains("worldwide|anywhere|remote", case=False, na=False), "work_mode"] = "onsite"

In [147]:
df.head()

,title,company,location,work_mode,job_type,skills,salary,date_posted,experience_level,education,source,job_url
0,Data Scientist,"Comscore, Inc.","Pune, Maharashtra, India",onsite,fulltime,"[Linux, Python, R, SQL, Spark]",NaN,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/data-scientis...
1,"Senior Data Scientist, Agentic AI (Insurance U...",Guardian Life,"New York, New York, United States",onsite,fulltime,"[Git, PyTorch, Python, TensorFlow]",$118980 - $195465,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-data-s...
2,Financial Crimes - Senior Data Scientist,KeyBank,"Cleveland, Ohio, United States",onsite,fulltime,"[Python, SAS]",$94000 - $175000,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/financial-cri...
3,"Research Scientist – Computer Graphics, Vision...",Eyeline,"Los Angeles, California, United States",onsite,fulltime,[Python],$100000 - $320000,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/research-scie...
4,Emerging Talent – Computer Vision Engineering ...,Baker Hughes,"Florence, Tuscany, Italy",onsite,fulltime,[Python],NaN,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/emerging-tale...

In [148]:
df["work_mode"].value_counts()

work_mode
onsite    3616
remote     674
Name: count, dtype: int64

### Salary field cleanup

In [149]:
df["salary_min"] = df["salary"].str.extract(r'\$(\d+[\d,]*)').replace(',', '', regex=True).astype(float)
df["salary_max"] = df["salary"].str.extract(r'-\s*\$(\d+[\d,]*)').replace(',', '', regex=True).astype(float)

df.rename(columns={"salary": "salary_avg"}, inplace=True)
df["salary_avg"] = (df["salary_min"] + df["salary_max"]) / 2

In [150]:
df.head()

,title,company,location,work_mode,job_type,skills,salary_avg,date_posted,experience_level,education,source,job_url,salary_min,salary_max
0,Data Scientist,"Comscore, Inc.","Pune, Maharashtra, India",onsite,fulltime,"[Linux, Python, R, SQL, Spark]",NaN,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/data-scientis...,NaN,NaN
1,"Senior Data Scientist, Agentic AI (Insurance U...",Guardian Life,"New York, New York, United States",onsite,fulltime,"[Git, PyTorch, Python, TensorFlow]",157222.5,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/senior-data-s...,118980.0,195465.0
2,Financial Crimes - Senior Data Scientist,KeyBank,"Cleveland, Ohio, United States",onsite,fulltime,"[Python, SAS]",134500.0,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/financial-cri...,94000.0,175000.0
3,"Research Scientist – Computer Graphics, Vision...",Eyeline,"Los Angeles, California, United States",onsite,fulltime,[Python],210000.0,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/research-scie...,100000.0,320000.0
4,Emerging Talent – Computer Vision Engineering ...,Baker Hughes,"Florence, Tuscany, Italy",onsite,fulltime,[Python],NaN,2026-03-09 00:00:00+00:00,NaN,NaN,datasciencejobs,https://datasciencejobs.com/jobs/emerging-tale...,NaN,NaN

### Dropping duplicates

In [151]:
print(f"Before: {df.shape}")
df.drop_duplicates(subset=['job_url'], inplace=True)
print(f"After: {df.shape}")

Before: (4290, 14)
After: (4284, 14)

In [152]:
df["job_type"].value_counts()

job_type
fulltime    3243
contract       3
Name: count, dtype: int64

### Saving clean file

In [ ]:
df.to_csv("data/clean_jobs.csv", index=False)

: